### ISSUE TITLE
chest:elytra function doesn't work on servers

### ISSUE THREAD

**Issue by Beanbag141** [SFort/MC-SurvivalFlight#13]
We had both the chest:elytra and the beacon functions on our server config, we couldn't get creative flight. I took the chest:elytra function out and we were able to fly. 

Working creative_flight.script on the server: 
[
    beacon;
]

Not working creative_flight.script on the server: 
[
    beacon;
    chest: elytra;
]

on the not working file, we weren't able to fly at all, with the working file we were able to fly without an elytra within range of a beacon.

**Comment by SFort** [comment]
which survivalflight/fscript/minecraft version?

**Comment by Beanbag141** [comment]
> which survivalflight/fscript/minecraft version?

minecraft version 1.19 
most recent version of survivalflight

**Comment by SFort** [comment]
tested on mc1.19.2 and mc1.19 (just in case)
survivalflight1.2.4 with fscript 3.1.6
works with those scripts.

(just making sure you do want both beacon and elytra required and the same time if you want either you need to use the `()` brackets)

please run the game with the broken script and send over `.minecraft/logs/latest.log`

**Comment by Beanbag141** [comment]
> tested on mc1.19.2 and mc1.19 (just in case) survivalflight1.2.4 with fscript 3.1.6 works with those scripts.
> 
> (just making sure you do want both beacon and elytra required and the same time if you want either you need to use the `()` brackets)
> 
> please run the game with the broken script and send over `.minecraft/logs/latest.log`

Could the brackets be the reason it isn't working?

**Comment by SFort** [comment]
i don't know what your trying todo.
if you're trying to require both elytra and beacon then the script is correct and work at least when i try it.
if you want either you should use `()` brackets instead

**Comment by Beanbag141** [comment]
> 

I'm trying to make it so you need both an elytra and a beacon to be able to fly. Also, it works in singleplayer, but when we try and copy those same files over to our server it doesn't work.

**Comment by SFort** [comment]
can't reproduce (is fancy dev speak for "idk lol works for me").

you're just gonna have to try stuff
like run it without any other mods / datapacks / try a diffrent world / maybe you accidently put the script in the wrong file i have no clue

can also send me the server files if you like, but not much i can do if i can't even tell there's a problem

**Comment by SFort** [comment]
might be using a mod that replaces the elytra item?
idk i can't really help with no debug info to go on. (logs)
hope you managed to figure it out
