### ISSUE TITLE
Unsure about flight failed effect

### ISSUE THREAD

**Issue by DCobley** [SFort/MC-SurvivalFlight#15]
Hello!

So ive been testing out this mod, and have been successful getting it to work how I want it to. But I've attempted to edit the flightfailedeffect config, using the example given (slow_falling;20). But it doesn't seem to work, which I'm not sure if its an issue with the mod or me misunderstanding how it works.

In my case I have a check to see if there is a beacon nearby, and if the jump boost effect is active (Which works). I then want the slow falling effect for people who are flying and then leave the radius of the beacon. Any help is appreciated!

![image](https://user-images.githubusercontent.com/9076948/218303037-37ed7665-0d19-408e-97c3-65e35fa75304.png)

**Comment by SFort** [comment]
the duration is in ticks, 20ticks is 1 second, this isn't enough to prevent fall damage, maybe 200 will do.
i hope that was the misunderstanding and it works, because i can't reproduce it my side.

**Comment by DCobley** [comment]
After a little more testing, it works on singleplayer, but that config doesn't seem to work on a server.

**Comment by SFort** [comment]
well this is the second time someone is having wierd client/server issues (#13).
it works on a server when i test it
make sure the config is set server-side, maybe reload the server to make absolutley sure? check the server log for errors, try with only survivalflight/fscript installed?

**Comment by DCobley** [comment]
Thanks for the quick replies! I removed all the mods and it did indeed work, luckily I found the mod causing the issues quickly, which is Essential Commands. A little annoying considering we use it for our housing system, not sure why it would be causing the issues though.

**Comment by SFort** [comment]
sweet, something i can work with, will look into when i can

**Comment by SFort** [comment]
yup my fault i just forgot to call it when playerAbilityLib is installed (a dependency of Essential Commands).
released for 1.19.3, tell me if you need a backport

**Comment by DCobley** [comment]
Thank you for the quick turnaround, super appreciated, and im on 1.19.3 so im good!
