### ISSUE TITLE
Overlapping beacons issue with Beacon requirement

### ISSUE THREAD

**Issue by DCobley** [SFort/MC-SurvivalFlight#16]
Hello!

So an issue I've run into is to do with overlapping beacons and the beacon requirement.

My scenario:
- I have two beacons with an overlapping radius, so in theory I should be able to move between these beacons with no issue. 
- Whenever I get out of the radius of the -first- beacon, my flight failure effect activates which I have set to slow falling. This always happens between moving from the first beacon, to the second beacon, but not always from the second to the first beacon (some kinda server beacon priority perhaps?)

Any help is appreciated!

**Comment by SFort** [comment]
at the time of programming that bit, i didn't really want to overcomplicate it,
so it just uses the bounding box of whatever beacon was closest last status effect refresh.
which should still be fine as long as as you're not moving too fast.
you might wanna use `sf_beacon_delayed` instead of `sf_beacon` for now as it ignores the range and just uses the effect duration?
but ye have to figure this out when i can.

**Comment by SFort** [comment]
are the beacons diffrent levels? if beacon 1 has a smaller range it would still be considered closer, which might be why this is happening (~~i should have used remaining range instead of proximity i guess~~, will redo to account for it in a less hacky way)

**Comment by DCobley** [comment]
The beacons are the same level so unfortunately isn't due to that, and speed doesn't seem to have an effect when moving between (i literally tapped w to just outside of the radius of one of the beacons and the flight failed effect instantly activated).

**Comment by SFort** [comment]
ah, they probably have a diffrent height then, because i can't immagine what else it could be

**Comment by DCobley** [comment]
Unfortunately its not that either, went into a superflat world with only SurvivalFlight and had the same effect.

https://user-images.githubusercontent.com/9076948/220272629-21f2e578-17ba-4a5a-a5df-3a9404c128d7.mp4

Im using the Jump Boost effect from the beacon to do what I want for now even if it does make it a bit more OP than just beacons

**Comment by SFort** [comment]
it should be as good as i can reasonably make it in the [1.3.2](https://github.com/SFort/MC-SurvivalFlight/releases/tag/r1.3.2) update.
i don't really want to make beacons less performant then they are, so hope this is good enough.
(as the beacons might just be too far away for the vanilla effect refresh to be timely enough)
(in case you need it for a pack, i intend to hold of the curse release for a bit, mosly in case i missed something again, that's obvious to you)

**Comment by SFort** [comment]
an easy way to test if it's vanilla timings, is set each of the beacons to a diffrent effect, if you just don't get the other effect by the time you reach the other beacon.
then there isn't anything i can reasonably do and if that's the case you might wanna use the delayed varient of the condition.

**Comment by DCobley** [comment]
Sorry for the delayed reply, But it seems to work! Ive gone back and forth quite a lot between beacons and it only extremely rarely seems activate the flightfail which I think from testing I can just fix by bringing the beacons a little closer together. So thank you! I really appreciate it
