### ISSUE TITLE
[Feature Suggestion/Bug?] Only activate Flight Failure if you are actually flying

### ISSUE THREAD

**Issue by DCobley** [SFort/MC-SurvivalFlight#17]
Im not entirely sure if this is intended or not, but either way, it would be nice if the flight failure only activates when you are actively flying. At the moment when I leave the range of a beacon while walking for example it will set off slow falling which results in walking down stairs a bit slower than intended for a little bit haha

**Comment by SFort** [comment]
ye it shouldn't, guessing i patched it too carelesly when fixing #15
