### ISSUE TITLE
How do i just simply enable flight?

### ISSUE THREAD

**Issue by Crykenpie** [SFort/MC-SurvivalFlight#20]
I just want to be able to enable flight in survival without needing any special items needed or anything. just simply have it enabled for my solo world all the time. Do i just open the config file for survivalflight and change false to true? I'm not good with understanding scripts and such, so apologies if my question seems dumb.

**Comment by SFort** [comment]
>change false to true

yup that will work
(the file you're looking for is `config/SurvivalFlight/creative_flight.script`).

in case you do wanna have conditions you can also just use it as a semi-normal config, i tried to make it simple.
(see the pinned issue "how do i use this mod" and just use the first bit without adding any brackets)
