### ISSUE TITLE
code doesn't save on multiplayer

### ISSUE THREAD

**Issue by ThatOneBee** [SFort/MC-SurvivalFlight#24]
when i make any sort of code on a multiplayer server and leave the ui the code gets deleted, not from the saved code though, just the active one

**Comment by SFort** [comment]
the UI saves it on the client you have to manually copy it over to the server ATM and then if the server is running run /survivalflight reload

**Comment by ThatOneBee** [comment]
ooh that's probably it, i'm going to check now thx

**Comment by ThatOneBee** [comment]
the command doesn't exist

**Comment by ThatOneBee** [comment]
do I type the command in chat?

**Comment by SFort** [comment]
the command is `/survivalflight reload` and for it to load it needs fabric api installed and be enabled in the configs.

you can also just restart the server to apply the new configs

**Comment by ThatOneBee** [comment]
oh, it worked thx
