### ISSUE TITLE
Cant get mod to work

### ISSUE THREAD

**Issue by FuzzyL16** [SFort/MC-SurvivalFlight#27]
Hello I have found your mod, but I can't seem to get it to work. When this mod is installed should you be able to fly without any restrictions? 
If so I cannot, I have tried to add some scripting but still doesn't see to do anything, I have used the Client Side mod to try and code up a Script but it also seems to not change anything to the file once downloaded btw I'm using a Aternos server and Aternos doesn't allow me to upload files with .script so I cant do it manually. Is there anything I can do to get this to work? 

The Mod does work on Single Player but not on the Aternos Server

**Comment by SFort** [comment]
if aternos allows you to rename files you can just temporarily change it to .txt then back to .script

or maybe create the file and edit it? (i really am not fammiliar with the restrictions of your host)

guess needed to update the mod to actually allow changing the server anyways

**Comment by SFort** [comment]
Added /survivalflight script flight INSERT_SCRIPT_HERE.
