### ISSUE TITLE
config file is not created at startup

### ISSUE THREAD

**Issue by GotHuBou** [SFort/MC-SurvivalFlight#29]
Hey,

I'm trying to install SurvivalFlight on my server but the associated file in the config file is not created when I start the server... We are running on 1.20.1, I did upload the files survivalflight-1.3.3.jar and fscript-3.2.2+1.19.4.jar, did I miss something ?
I tried to create a file SurvivalFlight in the directory config and then uploaded a script in /config/SurvivalFlight, but I believe some other files are supposed to be there ?

Thanks for your help :)
Gothrers

**Comment by SFort** [comment]
do you have fabric installed?

**Comment by GotHuBou** [comment]
Nope, I'm using forge

**Comment by SFort** [comment]
that'll do it, fscript/survivalflight ware never ported to forge, sorry but i just have too many projects keeping them running is enough as is.

**Comment by GotHuBou** [comment]
Ohh ok, I missed that point when I downloaded the mod, my bad. Thanks for your answer though !
