### ISSUE TITLE
appears to fail loading on 1.16.5

### ISSUE THREAD

**Issue by superon** [SFort/MC-SurvivalFlight#3]
fails pretty much instantly with console reporting:
https://pastebin.com/W3ff4iHZ

**Comment by SFort** [comment]
you need java 16

**Comment by SFort** [comment]
which i guess is still kinda my fault since pre 1.17 versions are supposed to be java 8 compatble, will fix

**Comment by superon** [comment]
aha nice one :)

**Comment by SFort** [comment]
Fixed in 1.1.4-1.16
