### ISSUE TITLE
Elytraless elytra flight in single-player not functioning

### ISSUE THREAD

**Issue by lunathir** [SFort/MC-SurvivalFlight#5]
With update 1.1.8 (the latest version of FScript and SurvivalFlight) on Minecraft 1.18, it seems having "Allow gliding without an elytra" set true in general.conf completely overrides script function in single player, disabling elytra flight even when set to true in elytra_flight.script.

**Comment by SFort** [comment]
This apears to be a conflict with fabricAPI so in case you don't need fabricAPI disable it for now, will look into exactly what's happening tommorow (probably)

**Comment by lunathir** [comment]
Alrighty, and thanks again. It seems to work with elytras only still, so there's a minor correction there.
