### ISSUE TITLE
the server side crashed

### ISSUE THREAD

**Issue by monsters-97** [SFort/MC-SurvivalFlight#6]
This is the problem that has been bothering me for a month. 

It works fine in 1.17.1. I really like this mod!  So I want to use it in 1.18.1. But, when I run the fabric server, the server crashes

**mods:**
survivalflight-1.1.9.jar
modmenu-3.0.1.jar
fscript-2.1.0.jar
fabric-api-0.46.1+1.18.jar

I don't know if it needs any other mods. When I delete survival flight, the server will run normal. So I think the problem is in the survival flight

**Here is my powershell log**
MCDReforged 2.3.1 is starting up
MCDReforged is open source, u can find it here: https://github.com/Fallen-Breath
/MCDReforged
[MCDR] [22:49:59] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [22:49:59] [MainThread/INFO]: 编码 / 解码方式已设置为 utf-8 / cp936
[MCDR] [22:49:59] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [22:49:59] [MainThread/INFO]: - plugins
[MCDR] [22:49:59] [MainThread/INFO]: 解析处理器已设置为 vanilla_handler
[MCDR] [22:49:59] [MainThread/INFO]: MCDReforged正于Python 3.8.3环境中运行
[MCDR] [22:49:59] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [22:49:59] [TaskExecutor/INFO]: 没有插件变更; 已加载插件数: 2
[MCDR] [22:49:59] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms2G -Xmx4G -jar fabric-server-launch.jar nogui"
[MCDR] [22:49:59] [MainThread/INFO]: 服务端正在以 PID 10024 运行中
[Server] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture[0m
[Server] [22:50:00] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12[0m
[Server] [22:50:01] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12[0m
[Server] [22:50:01] [main/WARN]: Warnings were found![0m
[Server]  - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.
18+3ac43d9565 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)![0m
[Server]         - You should install any version of fabric-textures-v0 for theoptimal experience.[0m
[Server] [22:50:01] [main/INFO]: Loading 40 mods:[0m
[Server]        - fabric 0.46.1+1.18[0m
[Server]        - fabric-api-base 0.4.1+b4f4f6cd65 via fabric[0m
[Server]        - fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric[0m
[Server]        - fabric-biome-api-v1 6.0.1+ded849a965 via fabric[0m
[Server]        - fabric-command-api-v1 1.1.6+3ac43d9565 via fabric[0m
[Server]        - fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric[0m
[Server]        - fabric-containers-v0 0.1.18+d154e2c665 via fabric[0m
[Server]        - fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric[0m
[Server]        - fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric[0m
[Server]        - fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric[0m
[Server]        - fabric-entity-events-v1 1.4.5+6b21378a65 via fabric[0m
[Server]        - fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric[0m
[Server]        - fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric[0m
[Server]        - fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric[0m
[Server]        - fabric-item-api-v1 1.3.0+691a79b565 via fabric[0m
[Server]        - fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric[0m
[Server]        - fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric[0m
[Server]        - fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric[0m
[Server]        - fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric[0m
[Server]        - fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric[0m
[Server]        - fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric[0m
[Server]        - fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric[0m
[Server]        - fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric[0m
[Server]        - fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric[0m
[Server]        - fabric-particles-v1 0.2.9+526dc1ac65 via fabric[0m
[Server]        - fabric-registry-sync-v0 0.9.0+befed49e65 via fabric[0m
[Server]        - fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabri
c[0m
[Server]        - fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric[0m
[Server]        - fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
[0m
[Server]        - fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric[0m
[Server]        - fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric[0m
[Server]        - fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric[0m
[Server]        - fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric[0m
[Server]        - fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric[0m
[Server]        - fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric[0m
[Server]        - fabricloader 0.12.12[0m
[Server]        - fscript 2.1.0[0m
[Server]        - java 17[0m
[Server]        - minecraft 1.18.1[0m
[Server]        - survivalflight 1.1.9[0m
[Server] [22:50:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/%e6%88%9a%e5%bf%97%e4%bc%9f/%e6%88%91%e7%9a%84%e4%b8%96%e7%95%8c%e6%95%b4%e5%90%88%e5%8c%85/1.18.1/%e6%9c%8d%e5%8a%a1%e7%ab%af/%e3%80%9025566%e3%80%91survival/server/libraries/net/fabricmc/spone-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER[0m
[Server] [22:50:01] [main/INFO]: Compatibility level set to JAVA_16[0m
[Server] [22:50:07] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zcb000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy tosuppress this warning.[0m
[Server] [22:50:09] [main/WARN]: tf.ssf.sfort.survivalflight #6[0m
[Server] java.lang.NumberFormatException: For input string: "null"[0m
[Server] [22:50:09] [main/WARN]: tf.ssf.sfort.survivalflight #16[0m
[Server] java.lang.NumberFormatException: For input string: "null"[0m
[Server] [22:50:09] [main/INFO]: tf.ssf.sfort.survivalflight successfully loaded config file[0m
[Server] [22:50:09] [main/INFO]: tf.ssf.sfort.survivalflight successfully loaded flight script file[0m
[Server] [22:50:09] [main/INFO]: tf.ssf.sfort.survivalflight successfully loaded elytra script file[0m
[Server] [22:50:09] [main/INFO]: tf.ssf.sfort.survivalflight successfully loaded elytra boost script file[0m
[Server] [22:50:09] [main/FATAL]: Failed to start the minecraft server[0m
[Server] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'survivalflight'![0m
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabricloader0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?][0m
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod) ~[?:?][0m
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMthodAccessorImpl.java:77) ~[?:?][0m
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?][0m
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?][0m
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?][0m
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?][0m
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod) ~[?:?][0m
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?][0m
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?][0m
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?][0m
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?][0m
[Server] Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437[0m
[Server]        at tf.ssf.sfort.survivalflight.Config.onInitialize(Config.java:122) ~[survivalflight-1.1.9.jar:?][0m
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        ... 15 more[0m
[Server] Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437[0m
[Server]        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?][0m
[Server]        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?][0m
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?][0m
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?][0m
[Server]        at tf.ssf.sfort.survivalflight.Config.onInitialize(Config.java:122) ~[survivalflight-1.1.9.jar:?][0m
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?][0m
[Server]        ... 15 more[0m
[MCDR] [22:50:10] [MainThread/[32mINFO[0m]: 等待服务端进程停止[0m
[MCDR] [22:50:10] [MainThread/[32mINFO[0m]: 服务端进程返回代码: 0[0m
[MCDR] [22:50:10] [MainThread/[32mINFO[0m]: 服务端已关闭[0m
[MCDR] [22:50:10] [MainThread/[32mINFO[0m]: 正在关闭 MCDR[0m
[MCDR] [22:50:10] [MainThread/[32mINFO[0m]: 正在关闭高级控制台[0m
[MCDR] [22:50:10] [MainThread/INFO]: bye

**Comment by SFort** [comment]
[1.2.0](https://github.com/SFort/MC-SurvivalFlight/releases/download/r1.2.0/survivalflight-1.2.0.jar) might fix this

**Comment by monsters-97** [comment]
This problem is solved. Thank you!
